<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <!-- NuGet Package Configuration -->
    <IsPackable>true</IsPackable>
    <PackageId>MedflixAPI</PackageId>
    <Version>1.0.0</Version>
    <Authors>mohdje</Authors>
    <Description>A .NET class library to search for movies, series, subtitles, and torrents.</Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/mohdje/MedflixAPI</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageProjectUrl>https://github.com/mohdje/MedflixAPI</PackageProjectUrl>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <PlatformTarget>AnyCPU</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="HtmlAgilityPack" Version="1.11.29" />
  </ItemGroup>
</Project>
